server:
  port: 31000
#  http2:
#    enabled: true
spring:
  application:
    # 程序名称
    name: bbb
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: GMT+8
  redis:
    host: 119.23.25.159
    port: 6379
    database: 7
    password: lidashuang
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: aaaa
          uri: lb://aaa
          predicates:
            - Path=/a/**
          filters:
            - name: P6eCleaner
            - name: P6eLog
            - name: P6eCrossDomain
            - name: P6eReferer
              args:
                whiteList:
                  - '*'
            - name: P6eAuth
#            - name: P6eJurisdiction
            - name: StripPrefix
              args:
                parts: 1
