server:
  port: 20000

spring:
  datasource:
    url: jdbc:mysql://119.23.25.159:3306/p6e?autoReconnect=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password: Root1234!@#$
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  application:
    name: aaa

