server:
  port: 20000

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://119.23.25.159:3306/p6e?autoReconnect=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password: Root1234!@#$
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

